packages: []

catalog:
catalogs:
  build:
    '@nuxt/eslint': ^1.3.0
    '@unocss/eslint-config': ^66.1.0-beta.10
    '@unocss/nuxt': ^66.1.0-beta.10
    '@vueuse/nuxt': ^13.1.0
    nuxt: ^3.16.2
    unocss: ^66.1.0-beta.10
    unplugin: ^2.2.2
    vite: ^6.2.5

  dev:
    '@antfu/eslint-config': ^4.11.0
    eslint: ^9.24.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    vue-tsc: ^2.2.8

  frontend:
    '@tresjs/cientos': ^4.3.0
    '@tresjs/nuxt': ^3.0.8
    '@tresjs/post-processing': ^2.3.1
    '@vueuse/core': ^13.1.0
    three: ^0.176.0
    vue: ^3.5.13
  icons:
    '@iconify-json/carbon': ^1.2.8
    '@iconify-json/twemoji': ^1.2.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
